### ISSUE TITLE
prev != self.prev

### ISSUE THREAD

**Issue by CaptainQwark** [annttu/Diamond-collectors#1]
Hi, thanks for sharing the zfs arc collector, but there is a serious bug in it:

On line 75 you have: `prev = copy.deepcopy(self.cur)` but a few lines later you use `self.prev`. `self.prev` is not the same as `prev`! Either use self.prev on line 75 or drop the `self.` on the lines below that. In the latter case you can remove `self.prev` from the `__init__` as well.

Without this fix the collected values are way off for every metric.

**Comment by annttu** [comment]
Thanks for noticing this! I fixed this in commit 9abe896.

**Comment by CaptainQwark** [comment]
Nice, thanks!

Alex.
